name: appimage
on: push
jobs:
  appimage-create:
    strategy:
      matrix:
        runner: [ubuntu-20.04, ubuntu-22.04-arm]
        include:
          - runner: ubuntu-20.04
            arch: x86_64
          - runner: ubuntu-22.04-arm
            arch: arm64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt-get update && sudo apt-get install -y zlib1g-dev liblzo2-dev liblzma-dev libbz2-dev scons libfuse3-dev libzstd-dev curl
      - name: build lzopfs
        run: scons
      - name: fetch linuxdeploy
        run: 'curl -Lo linuxdeploy https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-$(uname -m).AppImage && chmod +x linuxdeploy'
      - name: build appimage
        run: touch lzopfs.svg && ./linuxdeploy --appdir AppDir --executable lzopfs -i lzopfs.svg --output appimage --create-desktop-file
      - uses: actions/upload-artifact@v4
        with:
          name: lzopfs-${{ matrix.arch }}.AppImage
          path: lzopfs-${{ matrix.arch }}.AppImage
